[book]
authors = ["Nicholas Fleck"]
language = "en"
multilingual = false
src = "src"
title = "Rant Reference"
google-analytics = "UA-179100611-2"

[output.html]
#additional-js = ["theme/hljs_rant.js"]
git-repository-url = "https://github.com/rant-lang/reference"