[book]
title = "Rant Reference"
description = "The Rant Reference documents the Rant language and standard library."
authors = ["Berkin"]
language = "en"
src = "src"

[output.html]
additional-css = ["theme/custom.css"]
#additional-js = ["theme/hljs_rant.js"]
mathjax-support = true
cname = "docs.rant-lang.org"
default-theme = "ayu"
google-analytics = "UA-179100611-2"
git-repository-url = "https://github.com/rant-lang/reference"